# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clock_speed', models.FloatField(max_length=5)),
                ('cores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('benchmark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(blank=True)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('battery', models.FloatField(max_length=2)),
                ('price', models.IntegerField(blank=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.CPU')),
                ('gpu', models.ManyToManyField(to='laptops.GPU')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.Manufacturer'),
        ),
    ]
