# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_auto_20170420_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
