# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0005_auto_20170420_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
