# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0007_remove_gpu_benchmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='storage',
        ),
        migrations.AddField(
            model_name='laptop',
            name='benchmark',
            field=models.IntegerField(blank=True, default=432),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='hdd',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='ssd',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
