# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0008_auto_20171209_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='benchmark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hdd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
